export enum AuthErrors {
  INVALID_EMAIL = 'INVALID_EMAIL',
  MISSING_NAME = 'MISSING_NAME',
  MISSING_PASSWORD = 'MISSING_PASSWORD',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
